services:
  - type: web
    name: portfolio-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_PROVIDER
        value: gmail
      - key: EMAIL_USER
        value: gebeyawbereket8@gmail.com
      - key: EMAIL_FROM
        value: gebeyawbereket8@gmail.com
      - key: EMAIL_TO
        value: gebeyawbereket8@gmail.com
      - key: EMAIL_PASS
        sync: false
